version: '2'
services:
    erestaurante-app:
        image: erestaurante
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://erestaurante-postgresql:5432/ERestaurante
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    erestaurante-postgresql:
        extends:
            file: postgresql.yml
            service: erestaurante-postgresql
